Update all contrib to current
Warmshowers upgrades 2012-02-22

Security and code updates will be made to the following projects: Admin role [adminrole-6.x-1.3], Advanced Poll [advpoll-6.x-1.x-dev], Browscap [browscap-6.x-1.3], Comment notify [comment_notify-6.x-1.6], Date [date-6.x-2.8], Devel [devel-6.x-1.26], Diff [diff-6.x-2.3], Embedded Media Field [emfield-6.x-1.26], Frequently Asked Questions [faq-6.x-1.13], Features [features-6.x-1.2], FileField [filefield-6.x-3.10], Front Page [front-6.x-1.3], Google Analytics [google_analytics-6.x-3.3], HTML Mail [htmlmail-6.x-2.62], Internationalization [i18n-6.x-1.10], ImageAPI [imageapi-6.x-1.10], ImageCache [imagecache-6.x-2.0-beta12], ImageField [imagefield-6.x-3.10], Job queue [job_queue-6.x-3.1], LoginToboggan [logintoboggan-6.x-1.10], Nagios monitoring [nagios-6.x-1.2], Nodequeue [nodequeue-6.x-2.11], Nodewords: D6 Meta Tags [nodewords-6.x-1.13], Pathauto [pathauto-6.x-1.6], Prepopulate [prepopulate-6.x-2.2], Registration Language [reglang-6.x-1.8], Reroute Email [reroute_email-6.x-1.2], Rules [rules-6.x-1.4], Token [token-6.x-1.18], User Delete [user_delete-6.x-1.4], Views [views-6.x-2.16], Views Bulk Operations (VBO) [views_bulk_operations-6.x-1.13], Wysiwyg [wysiwyg-6.x-2.4]

diff --git a/sites/all/modules/contrib/nagios/nagios-plugin/check_drupal b/sites/all/modules/contrib/nagios/nagios-plugin/check_drupal
--- a/sites/all/modules/contrib/nagios/nagios-plugin/check_drupal
+++ b/sites/all/modules/contrib/nagios/nagios-plugin/check_drupal
@@ -15,7 +15,7 @@ SSL=/bin/false
 
 PROGNAME=`/usr/bin/basename $0`
 PROGPATH=`echo $0 | sed -e 's,[\\/][^\\/][^\\/]*$,,'`
-REVISION=`echo '$Revision: 1.1.2.13 $' | sed -e 's/[^0-9.]//g'`
+REVISION=`echo '$Revision$' | sed -e 's/[^0-9.]//g'`
 
 temp=`mktemp`
 
@@ -24,7 +24,7 @@ if [[ -e $PROGPATH/utils.sh ]]; then
 elif [[ -e /usr/lib/nagios/plugins/utils.sh ]]; then
   . /usr/lib/nagios/plugins/utils.sh
 else
-  echo 'Could not find nagios utils include file!'
+  echo 'Could not find nagios utils include file! Set PROGPATH on line 17 of the check_drupal script.'
   exit 1
 fi
 
@@ -87,7 +87,6 @@ while test -n "$1"; do
       ;;
     -S)
       SSL=/bin/true
-      shift
       ;;
     -t) 
       timeout=$2
@@ -153,14 +152,14 @@ HTTP=`$GREP "HTTP/1" $temp`
 if [ "$RC" != 0 ]; then
   $ECHO "wget error: $RC: when accessing $hostname/$path. HTTP: $HTTP"
   $RM -f $temp
-  exit $STATE_CRITICAL
+  exit $STATE_UNKNOWN
 fi
 
 HTTP_CODE=`$ECHO "$HTTP" | awk '{print $2}'`
 if [ "$HTTP_CODE" != "200" ]; then
   $ECHO "HTTP returned an error code. HTTP: $HTTP"
   $RM -f $temp
-  exit $STATE_CRITICAL
+  exit $STATE_UNKNOWN
 fi
 
 DATA="`$GREP "nagios=" $temp | sed -e 's/^.*nagios=//g'`"
